# Generated by Django 5.2.7 on 2025-10-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_car_engine_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_for_rent',
            field=models.BooleanField(default=False, help_text='Car is available for rent'),
        ),
        migrations.AddField(
            model_name='car',
            name='is_for_sale',
            field=models.BooleanField(default=True, help_text='Car is for sale'),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rental price', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_week',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weekly rental price', max_digits=8, null=True),
        ),
    ]
