# Generated by Django 5.2.7 on 2025-10-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_car_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='car',
            name='longitude',
        ),
        migrations.AddField(
            model_name='car',
            name='postcode',
            field=models.CharField(blank=True, help_text='Postal code', max_length=20),
        ),
    ]
