# Generated by Django 5.2.7 on 2025-10-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='power',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Limousine'), ('suv', 'SUV/Geländewagen'), ('coupe', 'Coupé'), ('cabrio', 'Cabrio/Roadster'), ('wagon', 'Kombi'), ('van', 'Van/Kleinbus'), ('pickup', 'Pick-up'), ('hatchback', 'Kleinwagen')], default='sedan', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='co2_emission',
            field=models.IntegerField(blank=True, help_text='CO2-Emission in g/km', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Kraftstoffverbrauch l/100km', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='emission_class',
            field=models.CharField(blank=True, help_text='Schadstoffklasse', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='emission_sticker',
            field=models.CharField(blank=True, help_text='Umweltplakette', max_length=20),
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.TextField(blank=True, help_text='Ausstattung (comma separated)'),
        ),
        migrations.AddField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, help_text='Erstzulassung', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='power_hp',
            field=models.IntegerField(default=100, help_text='Leistung in PS'),
        ),
        migrations.AddField(
            model_name='car',
            name='power_kw',
            field=models.IntegerField(blank=True, help_text='Leistung in kW', null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='previous_owners',
            field=models.IntegerField(default=0, help_text='Vorbesitzer'),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(blank=True, help_text='Fahrzeugidentifikationsnummer', max_length=17),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('black', 'Schwarz'), ('white', 'Weiß'), ('silver', 'Silber'), ('gray', 'Grau'), ('blue', 'Blau'), ('red', 'Rot'), ('green', 'Grün'), ('yellow', 'Gelb'), ('orange', 'Orange'), ('brown', 'Braun'), ('beige', 'Beige'), ('gold', 'Gold')], max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('new', 'Neu'), ('used', 'Gebraucht'), ('damaged', 'Unfallfahrzeug'), ('vintage', 'Oldtimer')], default='used', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Hubraum in cm³', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Diesel'), ('electric', 'Elektro'), ('hybrid', 'Hybrid'), ('lpg', 'Autogas (LPG)'), ('cng', 'Erdgas (CNG)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(help_text='Kilometerstand'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Schaltgetriebe'), ('automatic', 'Automatik'), ('semi_automatic', 'Halbautomatik')], max_length=20),
        ),
    ]
