# Generated by Django 5.2.7 on 2025-10-23 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_car_power_car_body_type_car_co2_emission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(blank=True, help_text='Hubraum in cm³', null=True),
        ),
    ]
