# Generated by Django 5.2.7 on 2025-10-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Januar'), (2, 'Februar'), (3, 'März'), (4, 'April'), (5, 'Mai'), (6, 'Juni'), (7, 'Juli'), (8, 'August'), (9, 'September'), (10, 'Oktober'), (11, 'November'), (12, 'Dezember')], null=True),
        ),
    ]
